language: ruby
rvm:
  - "1.9.3"

script:
  #- RAILS_ENV=test bundle exec rake app:db:migrate --trace
  #- bundle exec rake app:db:test:prepare
  - bundle exec rake spec --rakefile .rspec-travis

branches:
  only:
    - master

bundler_args: --without development production

